apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
FooterRoyal Philips
Philips Privacy Notice
Royal Philips
Royal Philips
Philips Pri
